/**
 * supabase.ts — Generated types
 *
 * This file is AUTO-GENERATED by the Supabase CLI.
 * Do NOT hand-edit. Regenerate whenever the schema changes:
 *
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts
 *
 * The Database type here is a placeholder so the app compiles before
 * you run the generator. Replace the entire file with the CLI output.
 *
 * After generating:
 *  - Services use Database['public']['Tables']['TravelAppExpenses']['Row'] internally
 *  - Then immediately map to the domain types from domain.ts
 *  - Components never import from this file
 */

// src/types/supabase.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
    public: {
        Tables: {
            TravelAppUsers: {
                Row: {
                    id: string;
                    device_uuid: string;
                    display_name: string | null;
                    avatar_color: string | null;
                    created_at: string;
                    last_seen: string;
                };
                Insert: {
                    id?: string;
                    device_uuid: string;
                    display_name?: string | null;
                    avatar_color?: string | null;
                    created_at?: string;
                    last_seen?: string;
                };
                Update: {
                    id?: string;
                    device_uuid?: string;
                    display_name?: string | null;
                    avatar_color?: string | null;
                    created_at?: string;
                    last_seen?: string;
                };
                Relationships: [];
            };
            TravelAppTrips: {
                Row: {
                    id: string;
                    name: string;
                    join_code: string | null;
                    join_code_expires_at: string | null;
                    destination: string | null;
                    start_date: string | null;
                    end_date: string | null;
                    created_by_device: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    join_code?: string | null;
                    join_code_expires_at?: string | null;
                    destination?: string | null;
                    start_date?: string | null;
                    end_date?: string | null;
                    created_by_device: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    join_code?: string | null;
                    join_code_expires_at?: string | null;
                    destination?: string | null;
                    start_date?: string | null;
                    end_date?: string | null;
                    created_by_device?: string;
                    created_at?: string;
                };
                Relationships: [];
            };
            TravelAppMembers: {
                Row: {
                    id: string;
                    trip_id: string;
                    device_id: string | null;
                    display_name: string;
                    joined_at: string;
                    guest_token: string | null;
                };
                Insert: {
                    id?: string;
                    trip_id: string;
                    device_id?: string | null;
                    display_name: string;
                    joined_at?: string;
                    guest_token?: string | null;
                };
                Update: {
                    id?: string;
                    trip_id?: string;
                    device_id?: string | null;
                    display_name?: string;
                    joined_at?: string;
                    guest_token?: string | null;
                };
                Relationships: [
                    {
                        foreignKeyName: "TravelAppMembers_trip_id_fkey";
                        columns: ["trip_id"];
                        isOneToOne: false;
                        referencedRelation: "TravelAppTrips";
                        referencedColumns: ["id"];
                    }
                ];
            };
            TravelAppExpenses: {
                Row: {
                    id: string;
                    trip_id: string;
                    paid_by_member: string;
                    title: string;
                    category: string | null;
                    amount_money: number;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    trip_id: string;
                    paid_by_member: string;
                    title: string;
                    category?: string | null;
                    amount_money: number;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    trip_id?: string;
                    paid_by_member?: string;
                    title?: string;
                    category?: string | null;
                    amount_money?: number;
                    created_at?: string;
                    updated_at?: string;
                };
                Relationships: [
                    {
                        foreignKeyName: "TravelAppExpenses_paid_by_member_fkey";
                        columns: ["paid_by_member"];
                        isOneToOne: false;
                        referencedRelation: "TravelAppMembers";
                        referencedColumns: ["id"];
                    },
                    {
                        foreignKeyName: "TravelAppExpenses_trip_id_fkey";
                        columns: ["trip_id"];
                        isOneToOne: false;
                        referencedRelation: "TravelAppTrips";
                        referencedColumns: ["id"];
                    }
                ];
            };
            TravelAppSplits: {
                Row: {
                    id: string;
                    expense_id: string;
                    member_id: string;
                    share_money: number;
                    is_settled: boolean;
                };
                Insert: {
                    id?: string;
                    expense_id: string;
                    member_id: string;
                    share_money: number;
                    is_settled?: boolean;
                };
                Update: {
                    id?: string;
                    expense_id?: string;
                    member_id?: string;
                    share_money?: number;
                    is_settled?: boolean;
                };
                Relationships: [
                    {
                        foreignKeyName: "TravelAppSplits_expense_id_fkey";
                        columns: ["expense_id"];
                        isOneToOne: false;
                        referencedRelation: "TravelAppExpenses";
                        referencedColumns: ["id"];
                    },
                    {
                        foreignKeyName: "TravelAppSplits_member_id_fkey";
                        columns: ["member_id"];
                        isOneToOne: false;
                        referencedRelation: "TravelAppMembers";
                        referencedColumns: ["id"];
                    }
                ];
            };
        };
        Views: {
            [_ in never]: never;
        };
        Functions: {
            [_ in never]: never;
        };
        Enums: {
            [_ in never]: never;
        };
        CompositeTypes: {
            [_ in never]: never;
        };
    };
}